// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6sHp6avq01iHZwdiKC4Cw32ruAIx0lI',
    appId: '1:645534682403:web:3578ae91c601cf8f271096',
    messagingSenderId: '645534682403',
    projectId: 'wiem-app',
    authDomain: 'wiem-app.firebaseapp.com',
    storageBucket: 'wiem-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvHIGTpxIutGc1emfYwjJOQqjoV3dDKVQ',
    appId: '1:645534682403:android:aec898f6b352c5c8271096',
    messagingSenderId: '645534682403',
    projectId: 'wiem-app',
    storageBucket: 'wiem-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaWb8jODNyi0lo9JHyfw19r0gYHo0q1xs',
    appId: '1:645534682403:ios:71d7ade397a8784b271096',
    messagingSenderId: '645534682403',
    projectId: 'wiem-app',
    storageBucket: 'wiem-app.firebasestorage.app',
    iosBundleId: 'com.example.covoiturageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaWb8jODNyi0lo9JHyfw19r0gYHo0q1xs',
    appId: '1:645534682403:ios:71d7ade397a8784b271096',
    messagingSenderId: '645534682403',
    projectId: 'wiem-app',
    storageBucket: 'wiem-app.firebasestorage.app',
    iosBundleId: 'com.example.covoiturageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU6sHp6avq01iHZwdiKC4Cw32ruAIx0lI',
    appId: '1:645534682403:web:94c333623b3ca9db271096',
    messagingSenderId: '645534682403',
    projectId: 'wiem-app',
    authDomain: 'wiem-app.firebaseapp.com',
    storageBucket: 'wiem-app.firebasestorage.app',
  );

}