// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIXJEKe1ebAgozjWeYydS2UIW1OIwpWTo',
    appId: '1:826892544415:web:1539570d2d1f7957dcb5aa',
    messagingSenderId: '826892544415',
    projectId: 'coapp-6c703',
    authDomain: 'coapp-6c703.firebaseapp.com',
    storageBucket: 'coapp-6c703.firebasestorage.app',
    measurementId: 'G-P57E04CWQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABgYrx0eGaO3jknQDPxvxr-UsNbiC_Pmg',
    appId: '1:826892544415:android:3848a8acd5387dfbdcb5aa',
    messagingSenderId: '826892544415',
    projectId: 'coapp-6c703',
    storageBucket: 'coapp-6c703.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvH1ZZETupXkCmZ7hUf37SZqgTuovtzn8',
    appId: '1:826892544415:ios:4da8e41b2c4ed584dcb5aa',
    messagingSenderId: '826892544415',
    projectId: 'coapp-6c703',
    storageBucket: 'coapp-6c703.firebasestorage.app',
    iosBundleId: 'com.example.covoiturageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvH1ZZETupXkCmZ7hUf37SZqgTuovtzn8',
    appId: '1:826892544415:ios:4da8e41b2c4ed584dcb5aa',
    messagingSenderId: '826892544415',
    projectId: 'coapp-6c703',
    storageBucket: 'coapp-6c703.firebasestorage.app',
    iosBundleId: 'com.example.covoiturageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIXJEKe1ebAgozjWeYydS2UIW1OIwpWTo',
    appId: '1:826892544415:web:2869e2980e008baddcb5aa',
    messagingSenderId: '826892544415',
    projectId: 'coapp-6c703',
    authDomain: 'coapp-6c703.firebaseapp.com',
    storageBucket: 'coapp-6c703.firebasestorage.app',
    measurementId: 'G-PNQ5ZVTNZ7',
  );

}